# Generated by Django 5.2 on 2025-05-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
