# Generated by Django 5.2 on 2025-05-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_bulky",
            field=models.BooleanField(default=False),
        ),
    ]
