# Generated by Django 5.2 on 2025-05-02 09:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shopping_cart", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shoppingcart",
            old_name="payment_methods",
            new_name="payment_method",
        ),
    ]
