# Generated by Django 5.2 on 2025-05-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopping_cart", "0002_rename_payment_methods_shoppingcart_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppingcart",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "PENDING"), (2, "BOUGHT")], default=1
            ),
        ),
    ]
