# Generated by Django 5.2 on 2025-05-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopping_cart", "0003_shoppingcart_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppingcart",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Pending"), (2, "Bought"), (3, "Expired")], default=1
            ),
        ),
    ]
