# Generated by Django 5.2 on 2025-05-05 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("order", "0001_initial"),
        ("payment", "0001_initial"),
        ("product", "0001_initial"),
        ("shipping", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payment.paymentmethod",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(blank=True, to="product.product"),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shipping.shippingtype",
            ),
        ),
    ]
