# Generated by Django 5.2 on 2025-05-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Pending"),
                    (2, "Confirmed"),
                    (3, "Success"),
                    (4, "Cancelled"),
                ],
                default=1,
            ),
        ),
    ]
