# Generated by Django 5.2 on 2025-05-07 10:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_alter_order_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="shipping_type",
        ),
    ]
