# Generated by Django 5.2 on 2025-05-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0004_remove_order_shipping_type"),
        ("shipping", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverynote",
            name="shipping_type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Postal service"), (2, "Freight forwarding")]
            ),
        ),
        migrations.DeleteModel(
            name="ShippingType",
        ),
    ]
