# Generated by Django 5.2 on 2025-05-02 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0002_deliverynote"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverynote",
            name="shipping_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="shipping.shippingtype",
            ),
            preserve_default=False,
        ),
    ]
