# Generated by Django 5.2 on 2025-05-02 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0002_paymenttransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="payment_method",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="payment.paymentmethod",
            ),
            preserve_default=False,
        ),
    ]
