# Generated by Django 5.2 on 2025-05-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0003_paymenttransaction_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="amount",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
